apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  {{- if .Values.operatorGroup.selector.enabled }}
  labels:
  {{- range .Values.operatorGroup.selector.matchLabels }}
    {{ .name }}: {{ tpl .value $ }}
  {{- end }}
  {{- end }}

