apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.subscription.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  channel: {{ .Values.subscription.channel }}
  name: {{ .Values.subscription.operatorName }}
  source: {{ .Values.subscription.source }}
  sourceNamespace: {{ .Values.subscription.sourceNamespace }}
  installPlanApproval: {{ .Values.subscription.installPlanApproval }}
  {{- if .Values.subscription.startingCSV }}
  startingCSV: {{ .Values.subscription.startingCSV }}
  {{- end }}

