# Default values for toolbox.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

container:
  # image to be used in the pod
  image: quay.io/tlbueno/toolbox:latest

