{{- if eq .Values.operator.watch.mode "single" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: amq-broker-operator-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: amq-broker-operator-role
subjects:
- kind: ServiceAccount
  name: amq-broker-controller-manager
{{- end }}

