apiVersion: v1
kind: Pod
metadata:
  name: toolbox
  namespace: {{ .Values.namespace.name }}
spec:
  containers:
  - name: toolbox-container
    image: {{ .Values.container.image }}
    command: ["/bin/bash", "-c", "trap "exit" TERM ; while true; do sleep 3600; done"]