apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: toolbox
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: toolbox
  replicas: 1
  selector:
    matchLabels:
      app: toolbox
  template:
    metadata:
      labels:
        app: toolbox
    spec:
      containers:
      - name: toolbox-container
        image: {{ .Values.container.image }}
        imagePullPolicy: Always

