# Default values for broker-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# namespace where the operator will be installed
namespace: broker-operator-olm

operatorGroup:
  # operator group name
  name: broker-operator

subscription:
  # subscription name
  name: broker-operator-olm-sub

  # channel name
  channel: 7.11.x

  # operator package name
  operatorName: amq-broker-rhel8

  # catalog name from which the operator will be installed
  source: redhat-operators-catalog

  # catalog namespace
  sourceNamespace: olm

  # install plan approval type
  installPlanApproval: Automatic
  
  # the initial version of the operator to be installed
  # if empty it will not be used in the subscription 
  startingCSV: ""

