apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: {{ .Values.operatorGroup.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      broker-operator/managed-by: {{ .Values.subscription.name }}

