name: Release Charts

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch'
        required: true
  push:
    branches:
      - 'releases/**'

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - id: get_branch
        name: Get Branch Name
        run: |
          if [[ github.event.name == 'push' ]]; then
            echo "::set-output name=BRANCH_NAME ${{ github.ref }}"
          else
            echo "::set-output name=BRANCH_NAME ${{ github.event.inputs.branch }}"
          fi

      - name: Check branch name (optional input)
        run: |
          if [[ -z "${{ github.event.inputs.branch }}" ]]; then
            echo "Branch name not provided as input. Failing workflow."
            exit 1
          fi

      - name: Checkout specific branch (if push or input provided)
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.get_branch.outputs.BRANCH_NAME }}
          fetch-depth: 0
        if: steps.get_branch.outputs.BRANCH_NAME 

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Add repositories
        run: |
          helm repo add tlbueno https://tlbueno.github.io/helm-charts

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          skip_existing: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

